# Generated by Django 5.0.1 on 2024-01-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.DeleteModel(
            name='Task_image',
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Task Photos'),
        ),
    ]
