# Generated by Django 5.0.1 on 2024-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_images_delete_task_image_task_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_photos/', verbose_name='Task Photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(blank=True, to='tasks.image', verbose_name='Task Photos'),
        ),
    ]
