# Generated by Django 5.0.1 on 2024-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_photos_task_images_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='images',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
