# Generated by Django 5.0.1 on 2024-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=10),
        ),
    ]
